<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OrderProcessing.Api\OrderProcessing.Api.csproj" />
    <ProjectReference Include="..\..\src\OrderProcessing.Infrastructure\OrderProcessing.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\OrderProcessing.Application\OrderProcessing.Application.csproj" />
    <ProjectReference Include="..\..\src\OrderProcessing.Domain\OrderProcessing.Domain.csproj" />
  </ItemGroup>

</Project>
